name: Update Major Version Tag

on:
  release:
    types: [published]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update major version tag
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1)
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -f $MAJOR_VERSION $RELEASE_VERSION
          git push -f origin $MAJOR_VERSION
